config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :persons
  resources :companies
  root "persons#index"
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href=<%= root_path %>>Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href=<%= new_person_path %>>Crear Persona</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= new_company_path %>>Crear Empresa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= persons_path %>>Personas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= companies_path %>>Empresas</a>
        </li>
      </ul>
      <!--
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->
    </div>
  </div>
</nav>